[general]
email = "your_email@example.com"
# Replace with your actual email for Streamlit sharing notifications

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#F39C12"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F7"
textColor = "#333333"
font = "sans serif"