[google]
client_id = "your-google-client-id"
client_secret = "your-google-client-secret"
redirect_uri = "http://localhost:8501"

[apple]
client_id = "your-apple-client-id"
client_secret = "your-apple-client-secret"
redirect_uri = "http://localhost:8501"
key_id = "your-apple-key-id"
team_id = "your-apple-team-id"
